[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mi_proyecto"
version = "1.0"
authors = [{name = "Rubén Rodríguez Tártalo"}]
description = "Librería de ejemplo"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = []